/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.CharSheet;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Graeme
 */
public class CharacterSheet extends javax.swing.JDialog {

    /**
     * Creates new form MainCharacterPage
     *
     * @param parent
     * @param modal
     */
    public CharacterSheet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //Pulls information from CharacterData.java and displays in appropriate labels.
        this.lblNameInput.setText(CharacterData.charName);
        this.lblGenderInput.setText(CharacterData.charGender);
        this.lblRaceInput.setText(CharacterData.charRace);
        this.lblClassInput.setText(CharacterData.charClass);
        this.lblAllignInput.setText(CharacterData.charAlignment);

        //Will display Stats from CharacterClass.java in appropriate text fields
        this.txtSTR.setText(CharacterData.charSTR);
        this.txtDEX.setText(CharacterData.charDEX);
        this.txtINT.setText(CharacterData.charINT);
        this.txtWIS.setText(CharacterData.charWIS);
        this.txtCON.setText(CharacterData.charCON);
        this.txtCHA.setText(CharacterData.charCAR);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblRace = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        lblAllign = new javax.swing.JLabel();
        lblNameInput = new javax.swing.JLabel();
        lblGenderInput = new javax.swing.JLabel();
        lblRaceInput = new javax.swing.JLabel();
        lblClassInput = new javax.swing.JLabel();
        lblAllignInput = new javax.swing.JLabel();
        lblSTR = new javax.swing.JLabel();
        lblDEX = new javax.swing.JLabel();
        lblINT = new javax.swing.JLabel();
        lblCON = new javax.swing.JLabel();
        lblWIS = new javax.swing.JLabel();
        lblCHA = new javax.swing.JLabel();
        txtSTR = new javax.swing.JTextField();
        txtDEX = new javax.swing.JTextField();
        txtINT = new javax.swing.JTextField();
        txtCON = new javax.swing.JTextField();
        txtWIS = new javax.swing.JTextField();
        txtCHA = new javax.swing.JTextField();
        lblHP = new javax.swing.JLabel();
        lblARM = new javax.swing.JLabel();
        lblBONUS = new javax.swing.JLabel();
        txtHP = new javax.swing.JTextField();
        txtARM = new javax.swing.JTextField();
        txtBONUS = new javax.swing.JTextField();
        lblArmour = new javax.swing.JLabel();
        txtArmour = new javax.swing.JTextField();
        lblShield = new javax.swing.JLabel();
        txtShield = new javax.swing.JTextField();
        lvlWeapon = new javax.swing.JLabel();
        txtfieldWeapon = new javax.swing.JScrollPane();
        txtWeapon = new javax.swing.JTextArea();
        lblCurrentHP = new javax.swing.JLabel();
        txtfieldHp = new javax.swing.JScrollPane();
        txtCurrentHP = new javax.swing.JTextArea();
        lblAmmo = new javax.swing.JLabel();
        txtAmmo = new javax.swing.JTextField();
        lblEquip = new javax.swing.JLabel();
        txtfieldItems = new javax.swing.JScrollPane();
        txtEquip = new javax.swing.JTextArea();
        lblSkills = new javax.swing.JLabel();
        txtfieldSkills = new javax.swing.JScrollPane();
        txtSkills = new javax.swing.JTextArea();
        lblSpeed = new javax.swing.JLabel();
        txtSpeed = new javax.swing.JTextField();
        lblOther = new javax.swing.JLabel();
        txtfieldOther = new javax.swing.JScrollPane();
        txtOther = new javax.swing.JTextArea();
        lblLevel = new javax.swing.JLabel();
        lblEXP = new javax.swing.JLabel();
        txtLevel = new javax.swing.JTextField();
        txtEXP = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnD4 = new javax.swing.JButton();
        btnD6 = new javax.swing.JButton();
        btnD8 = new javax.swing.JButton();
        btnD10 = new javax.swing.JButton();
        btnD12 = new javax.swing.JButton();
        btnD20 = new javax.swing.JButton();
        border1 = new javax.swing.JLabel();
        border2 = new javax.swing.JLabel();
        border3 = new javax.swing.JLabel();
        border4 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DnD Character Sheet");
        setBounds(new java.awt.Rectangle(0, 0, 500, 550));
        setIconImage(null);
        setMaximumSize(new java.awt.Dimension(816, 590));
        setMinimumSize(new java.awt.Dimension(816, 584));
        setName("DnD Character Sheet"); // NOI18N
        setPreferredSize(new java.awt.Dimension(816, 615));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        lblName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblName.setText("Name");
        getContentPane().add(lblName);
        lblName.setBounds(210, 20, 40, 14);

        lblGender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGender.setText("Gender");
        getContentPane().add(lblGender);
        lblGender.setBounds(210, 40, 50, 14);

        lblRace.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRace.setText("Race");
        getContentPane().add(lblRace);
        lblRace.setBounds(210, 60, 40, 14);

        lblClass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblClass.setText("Class");
        getContentPane().add(lblClass);
        lblClass.setBounds(210, 80, 40, 14);

        lblAllign.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAllign.setText("Allign");
        getContentPane().add(lblAllign);
        lblAllign.setBounds(210, 100, 40, 20);

        lblNameInput.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblNameInput);
        lblNameInput.setBounds(260, 20, 190, 20);

        lblGenderInput.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblGenderInput);
        lblGenderInput.setBounds(260, 40, 190, 20);

        lblRaceInput.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblRaceInput);
        lblRaceInput.setBounds(260, 60, 190, 20);

        lblClassInput.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblClassInput);
        lblClassInput.setBounds(260, 80, 190, 20);

        lblAllignInput.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblAllignInput);
        lblAllignInput.setBounds(260, 100, 190, 20);

        lblSTR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSTR.setText("Strength");
        getContentPane().add(lblSTR);
        lblSTR.setBounds(20, 20, 80, 17);

        lblDEX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDEX.setText("Dexterity");
        getContentPane().add(lblDEX);
        lblDEX.setBounds(20, 60, 80, 17);

        lblINT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblINT.setText("Intelligence");
        getContentPane().add(lblINT);
        lblINT.setBounds(20, 100, 90, 17);

        lblCON.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCON.setText("Constitution");
        getContentPane().add(lblCON);
        lblCON.setBounds(20, 140, 90, 17);

        lblWIS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWIS.setText("Wisdom");
        getContentPane().add(lblWIS);
        lblWIS.setBounds(20, 180, 70, 17);

        lblCHA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCHA.setText("Charisma");
        getContentPane().add(lblCHA);
        lblCHA.setBounds(20, 220, 64, 17);
        getContentPane().add(txtSTR);
        txtSTR.setBounds(110, 20, 30, 30);
        getContentPane().add(txtDEX);
        txtDEX.setBounds(110, 60, 30, 30);
        getContentPane().add(txtINT);
        txtINT.setBounds(110, 100, 30, 30);
        getContentPane().add(txtCON);
        txtCON.setBounds(110, 140, 30, 30);
        getContentPane().add(txtWIS);
        txtWIS.setBounds(110, 180, 30, 30);
        getContentPane().add(txtCHA);
        txtCHA.setBounds(110, 220, 30, 30);

        lblHP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHP.setText("HP");
        getContentPane().add(lblHP);
        lblHP.setBounds(210, 160, 50, 17);

        lblARM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblARM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblARM.setText("ARM");
        getContentPane().add(lblARM);
        lblARM.setBounds(300, 160, 50, 17);

        lblBONUS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBONUS.setText("BONUS");
        getContentPane().add(lblBONUS);
        lblBONUS.setBounds(390, 160, 51, 17);

        txtHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtHP);
        txtHP.setBounds(210, 180, 50, 30);

        txtARM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtARM);
        txtARM.setBounds(300, 180, 50, 30);
        getContentPane().add(txtBONUS);
        txtBONUS.setBounds(390, 180, 50, 30);

        lblArmour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblArmour.setText("Armour");
        getContentPane().add(lblArmour);
        lblArmour.setBounds(481, 17, 80, 17);
        getContentPane().add(txtArmour);
        txtArmour.setBounds(481, 40, 161, 30);

        lblShield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblShield.setText("Shield");
        getContentPane().add(lblShield);
        lblShield.setBounds(480, 80, 70, 17);
        getContentPane().add(txtShield);
        txtShield.setBounds(480, 100, 161, 30);

        lvlWeapon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lvlWeapon.setText("Weapon / Attacks");
        getContentPane().add(lvlWeapon);
        lvlWeapon.setBounds(480, 140, 150, 17);

        txtWeapon.setColumns(20);
        txtWeapon.setRows(5);
        txtWeapon.setWrapStyleWord(true);
        txtfieldWeapon.setViewportView(txtWeapon);

        getContentPane().add(txtfieldWeapon);
        txtfieldWeapon.setBounds(476, 159, 166, 110);

        lblCurrentHP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCurrentHP.setText("Current HP");
        getContentPane().add(lblCurrentHP);
        lblCurrentHP.setBounds(210, 220, 78, 17);

        txtCurrentHP.setColumns(10);
        txtCurrentHP.setRows(5);
        txtCurrentHP.setWrapStyleWord(true);
        txtCurrentHP.setSelectionColor(new java.awt.Color(51, 51, 255));
        txtfieldHp.setViewportView(txtCurrentHP);

        getContentPane().add(txtfieldHp);
        txtfieldHp.setBounds(209, 237, 239, 100);

        lblAmmo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAmmo.setText("Ammo");
        getContentPane().add(lblAmmo);
        lblAmmo.setBounds(480, 270, 80, 17);
        getContentPane().add(txtAmmo);
        txtAmmo.setBounds(480, 290, 160, 30);

        lblEquip.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEquip.setText("Items / Equipment");
        getContentPane().add(lblEquip);
        lblEquip.setBounds(480, 330, 132, 17);

        txtEquip.setColumns(20);
        txtEquip.setRows(5);
        txtfieldItems.setViewportView(txtEquip);

        getContentPane().add(txtfieldItems);
        txtfieldItems.setBounds(476, 353, 166, 220);

        lblSkills.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSkills.setText("Skills");
        getContentPane().add(lblSkills);
        lblSkills.setBounds(210, 350, 80, 17);

        txtSkills.setColumns(20);
        txtSkills.setRows(5);
        txtfieldSkills.setViewportView(txtSkills);

        getContentPane().add(txtfieldSkills);
        txtfieldSkills.setBounds(209, 373, 239, 200);

        lblSpeed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSpeed.setText("Speed");
        getContentPane().add(lblSpeed);
        lblSpeed.setBounds(20, 270, 90, 17);
        getContentPane().add(txtSpeed);
        txtSpeed.setBounds(110, 270, 30, 30);

        lblOther.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblOther.setText("Other");
        getContentPane().add(lblOther);
        lblOther.setBounds(20, 330, 80, 22);

        txtOther.setColumns(20);
        txtOther.setRows(5);
        txtfieldOther.setViewportView(txtOther);

        getContentPane().add(txtfieldOther);
        txtfieldOther.setBounds(20, 350, 166, 221);

        lblLevel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLevel.setText("Level");
        getContentPane().add(lblLevel);
        lblLevel.setBounds(667, 14, 35, 17);

        lblEXP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEXP.setText("EXP");
        getContentPane().add(lblEXP);
        lblEXP.setBounds(675, 40, 28, 17);
        getContentPane().add(txtLevel);
        txtLevel.setBounds(706, 14, 100, 20);
        getContentPane().add(txtEXP);
        txtEXP.setBounds(707, 40, 99, 20);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(698, 542, 100, 23);

        btnD4.setText("Roll D4");
        btnD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD4);
        btnD4.setBounds(698, 513, 100, 23);

        btnD6.setText("Roll D6");
        btnD6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD6);
        btnD6.setBounds(698, 484, 100, 23);

        btnD8.setText("Roll D8");
        btnD8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD8);
        btnD8.setBounds(698, 455, 100, 23);

        btnD10.setText("Roll D10");
        btnD10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD10);
        btnD10.setBounds(698, 426, 100, 23);

        btnD12.setText("Roll D12");
        btnD12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD12ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD12);
        btnD12.setBounds(698, 397, 100, 23);

        btnD20.setText("Roll D20");
        btnD20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD20ActionPerformed(evt);
            }
        });
        getContentPane().add(btnD20);
        btnD20.setBounds(698, 368, 100, 23);

        border1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(border1);
        border1.setBounds(470, 10, 180, 570);

        border2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(border2);
        border2.setBounds(200, 10, 260, 130);

        border3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(border3);
        border3.setBounds(200, 150, 260, 430);

        border4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(border4);
        border4.setBounds(10, 10, 180, 570);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Graeme\\Pictures\\DnDCharacterImages\\tornpaperbkgrnd.jpg")); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(-240, -2080, 1070, 3032);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD4ActionPerformed
        //Displays Random number from 1 to 4
        int D4Roll;
        D4Roll = (int) (Math.random() * 4 + 1);
        JOptionPane.showMessageDialog(null, "You have rolled " + D4Roll);
    }//GEN-LAST:event_btnD4ActionPerformed

    private void btnD6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD6ActionPerformed
        //Displays Random number from 1 to 6
        int D6Roll;
        D6Roll = (int) (Math.random() * 6 + 1);
        JOptionPane.showMessageDialog(null, "You have rolled " + D6Roll);
    }//GEN-LAST:event_btnD6ActionPerformed

    private void btnD8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD8ActionPerformed
        //Displays Random number from 1 to 8
        int D8Roll;
        D8Roll = (int) (Math.random() * 8 + 1);
        JOptionPane.showMessageDialog(null, "You have rolled " + D8Roll);
    }//GEN-LAST:event_btnD8ActionPerformed

    private void btnD10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD10ActionPerformed
        //Displays Random number from 1 to 10
        int D10Roll;
        D10Roll = (int) (Math.random() * 10 + 1);
        JOptionPane.showMessageDialog(null, "You have rolled " + D10Roll);
    }//GEN-LAST:event_btnD10ActionPerformed

    private void btnD12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD12ActionPerformed
        //Displays Random number from 1 to 12
        int D12Roll;
        D12Roll = (int) (Math.random() * 12 + 1);
        JOptionPane.showMessageDialog(null, "You have rolled " + D12Roll);
    }//GEN-LAST:event_btnD12ActionPerformed

    private void btnD20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD20ActionPerformed
        //Displays Random number from 1 to 20
        int D20Roll;
        D20Roll = (int) (Math.random() * 20 + 1);
        JOptionPane.showMessageDialog(null, "You have rolled " + D20Roll);
    }//GEN-LAST:event_btnD20ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Closing window confirmation
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to close?", "Close", JOptionPane.YES_NO_CANCEL_OPTION) != JOptionPane.YES_OPTION) {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        } else {
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //Closes Window
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CharacterSheet dialog = new CharacterSheet(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel border1;
    private javax.swing.JLabel border2;
    private javax.swing.JLabel border3;
    private javax.swing.JLabel border4;
    private javax.swing.JButton btnD10;
    private javax.swing.JButton btnD12;
    private javax.swing.JButton btnD20;
    private javax.swing.JButton btnD4;
    private javax.swing.JButton btnD6;
    private javax.swing.JButton btnD8;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel lblARM;
    private javax.swing.JLabel lblAllign;
    private javax.swing.JLabel lblAllignInput;
    private javax.swing.JLabel lblAmmo;
    private javax.swing.JLabel lblArmour;
    private javax.swing.JLabel lblBONUS;
    private javax.swing.JLabel lblCHA;
    private javax.swing.JLabel lblCON;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblClassInput;
    private javax.swing.JLabel lblCurrentHP;
    private javax.swing.JLabel lblDEX;
    private javax.swing.JLabel lblEXP;
    private javax.swing.JLabel lblEquip;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGenderInput;
    private javax.swing.JLabel lblHP;
    private javax.swing.JLabel lblINT;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameInput;
    private javax.swing.JLabel lblOther;
    private javax.swing.JLabel lblRace;
    private javax.swing.JLabel lblRaceInput;
    private javax.swing.JLabel lblSTR;
    private javax.swing.JLabel lblShield;
    private javax.swing.JLabel lblSkills;
    private javax.swing.JLabel lblSpeed;
    private javax.swing.JLabel lblWIS;
    private javax.swing.JLabel lvlWeapon;
    private javax.swing.JTextField txtARM;
    private javax.swing.JTextField txtAmmo;
    private javax.swing.JTextField txtArmour;
    private javax.swing.JTextField txtBONUS;
    private javax.swing.JTextField txtCHA;
    private javax.swing.JTextField txtCON;
    private javax.swing.JTextArea txtCurrentHP;
    private javax.swing.JTextField txtDEX;
    private javax.swing.JTextField txtEXP;
    private javax.swing.JTextArea txtEquip;
    private javax.swing.JTextField txtHP;
    private javax.swing.JTextField txtINT;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextArea txtOther;
    private javax.swing.JTextField txtSTR;
    private javax.swing.JTextField txtShield;
    private javax.swing.JTextArea txtSkills;
    private javax.swing.JTextField txtSpeed;
    private javax.swing.JTextField txtWIS;
    private javax.swing.JTextArea txtWeapon;
    private javax.swing.JScrollPane txtfieldHp;
    private javax.swing.JScrollPane txtfieldItems;
    private javax.swing.JScrollPane txtfieldOther;
    private javax.swing.JScrollPane txtfieldSkills;
    private javax.swing.JScrollPane txtfieldWeapon;
    // End of variables declaration//GEN-END:variables

    private void setExtendedState(int MAXIMIZED_BOTH) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
